version = 1
dest = ".copilot-context"

[[sources]]
type = "repo"
name = "cargo-lib"
repo = "https://github.com/rust-lang/cargo.git"
branch = "gh-pages"
dest = "vendor/cargo-gh-pages"
files = ["!CNAME"]

[[sources]]
type = "url"
name = "api-specs"
url = "https://raw.githubusercontent.com/softprops/action-gh-release/refs/heads/master/README.md"
dest = "softprops/action-gh-release/README.md"

[[sources]]
type = "path"
name = "local-notes"
path = "README.md"
dest = "vendor/notes/README.md"

# Example 1: Create a simple version file
[[sources]]
type = "sh"
name = "simple-version"
script = 'echo "# Version Information" > version.md && echo "Created on: $(date)" >> version.md && echo "Rust version: $(rustc --version)" >> version.md'
dest = "metadata"

# Example 2: Generate directory listing
[[sources]]
type = "sh"
name = "dir-list"
script = 'ls -la > dir-list.txt'
dest = "info"

# Example 3: System information
[[sources]]
type = "sh"
name = "system-info"
script = 'uname -a > system-info.txt && echo "CPU: $(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Unknown")" >> system-info.txt'
dest = "system"
