version = 1

dest = ".copilot-context"

[[sources]]
name = "cargo-lib"
type = "repo"
repo = "https://github.com/rust-lang/cargo.git"
rm = ["CNAME"]
branch = "gh-pages"
dest = "vendor/cargo-gh-pages"

[[sources]]
name = "api-specs"
type = "url"
url = "https://svelte.dev/llms-full.txt"
dest = "vendor/svetle/llms-full.txt"

[[sources]]
name = "local-notes"
type = "path"
path = "README.md"
dest = "vendor/notes/README.md"
