# .github/workflows/ci-and-release.yml
name: build‑test
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  # ---------- Fast feedback loop ----------
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      # Installs toolchain + enables cache (~2‑3× speed‑up on reruns)
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true # piggy‑backs Swatinem/rust-cache

      - name: Cargo tests
        run: cargo test --all-features --locked --verbose

      - name: Lints & formatting
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo fmt --all -- --check
