# .github/workflows/ci-and-release.yml
name: build‑test‑release
on:
  push:
    branches: [main]
    tags: ["v*"] # Anything that looks like v1.2.3 triggers a release
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  # ---------- Fast feedback loop ----------
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      # Installs toolchain + enables cache (~2‑3× speed‑up on reruns)
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true # piggy‑backs Swatinem/rust-cache

      - name: Cargo tests
        run: cargo test --all-features --locked --verbose

      - name: Lints & formatting
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo fmt --all -- --check

  # ---------- Binary release on tag ----------
  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write # upload artefacts & edit Release
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo‑dist
        run: cargo install cargo-dist --locked

      - name: Add cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Build, package and publish – cargo‑dist auto‑detects the tag
      - name: Create multi‑platform release
        run: cargo dist release --tag ${{ github.ref_name }} --ci
