name: Release Rust CLI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          ext=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then ext=".exe"; fi
          BIN_NAME=mycli-${{ github.ref_name }}-${{ matrix.target }}$ext
          cp target/${{ matrix.target }}/release/mycli $BIN_NAME
        shell: bash

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: mycli-${{ github.ref_name }}-${{ matrix.target }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
